# Tensorflow - small introduction

> see also [Tensorflow tutorial](https://www.tensorflow.org/tutorials/quickstart/beginner)

Checking library install and version

In [13]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.3.0


Loading test database (MNIST)

<img src="https://upload.wikimedia.org/wikipedia/commons/2/27/MnistExamples.png">


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


Building a simple model

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.18413489, -0.88837886,  0.09438285,  0.16750255, -0.07148126,
        -0.4805155 ,  0.5883393 , -0.8011747 , -0.7050072 ,  0.24141923]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.09150059, 0.04524542, 0.12088784, 0.1300583 , 0.10241152,
        0.06803109, 0.19810945, 0.04936816, 0.05435155, 0.140036  ]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 961us/step - loss: 0.2991 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 2s 946us/step - loss: 0.1443 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 2s 969us/step - loss: 0.1093 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 2s 963us/step - loss: 0.0865 - accuracy: 0.9739
Epoch 5/5
1875/1875 [==============================] - 2s 947us/step - loss: 0.0737 - accuracy: 0.9773


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0801 - accuracy: 0.9750


[0.08010533452033997, 0.9750000238418579]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.7627506e-08, 4.6687592e-09, 3.4703662e-06, 7.9400015e-05,
        3.1176255e-12, 2.0776465e-08, 1.0508028e-13, 9.9991655e-01,
        9.7842261e-08, 3.7343199e-07],
       [1.4462685e-08, 2.9025643e-04, 9.9970728e-01, 4.2411563e-07,
        6.5756269e-16, 2.2134768e-07, 3.0681008e-07, 2.8726265e-14,
        1.4663216e-06, 2.9165066e-14],
       [1.0136307e-07, 9.9927551e-01, 1.7436450e-04, 1.0003037e-05,
        3.1400232e-05, 1.9203687e-06, 2.2667018e-06, 4.8299550e-04,
        2.0642325e-05, 7.8278066e-07],
       [9.9989498e-01, 2.8938238e-10, 1.3407367e-06, 3.8556674e-08,
        3.3698322e-07, 2.6454645e-06, 8.7932778e-05, 1.2342492e-05,
        1.7436362e-08, 3.7598718e-07],
       [8.8850056e-06, 2.9703448e-10, 1.0314368e-05, 6.0922595e-08,
        9.9785942e-01, 4.9881709e-07, 1.8979631e-06, 3.9982242e-05,
        1.9328432e-07, 2.0786913e-03]], dtype=float32)>